mybatis:
  mapper-locations: classpath:com/anishan/mapper/*.xml
  type-aliases-package: com.anishan.entity
  configuration:
    auto-mapping-behavior: full
spring:
  main:
    allow-circular-references: true

  application:
    name: LoginHomWork

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_homework_01
    username: anishan
    password: Han123456

  data:
    redis:
      database: 0
      jedis:
        pool:
          enabled: true

  mail:
    host: smtp.163.com
    username: a13920111@163.com
    password: 

